[build]
builder = "NIXPACKS"

[phases.setup]
nixPkgs = [
  "python311",
  "mesa",
  "libglvnd",
  "glib",
  "xorg.libSM",
  "xorg.libXext",
  "xorg.libXrender",
  "ffmpeg"
]

[phases.install]
cmds = ["pip install --no-cache-dir -r requirements.txt"]
