[phases.setup]
nixPkgs = ['python311', 'python311Packages.pip', 'python311Packages.virtualenv']

[phases.install]
cmds = [
  'python -m venv /opt/venv',
  '. /opt/venv/bin/activate && pip install --no-cache-dir -r requirements.txt'
]

[start]
cmd = '. /opt/venv/bin/activate && gunicorn app:app --bind 0.0.0.0:$PORT --timeout 300 --workers 1 --threads 2 --preload'
