[phases.setup]
nixPkgs = ['python311']

[phases.install]
cmds = ['python -m pip install --no-cache-dir -r requirements.txt']

[start]
cmd = 'gunicorn app:app --bind 0.0.0.0:$PORT --timeout 300 --workers 1 --threads 2 --preload'
